# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    keymap: qwerty
    format: bt
    artifact-name: totem_qwerty_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    keymap: qwerty
    format: bt
    artifact-name: totem_qwerty_right


  - board: seeeduino_xiao_ble
    shield: totem_left
    keymap: qwerty
    format: dongle
    artifact-name: totem_qwerty_dongle_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    keymap: qwerty
    format: dongle
    artifact-name: totem_qwerty_dongle_right

    
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    keymap: qwerty
    format: dongle
    artifact-name: totem_qwerty_dongle
    
  - board: seeeduino_xiao_ble
    shield: totem_dongle_prospector prospector_adapter
    keymap: qwerty
    format: dongle
    snippet: studio-rpc-usb-uart
    artifact-name: totem_qwerty_dongle_prospector
    
  - board: seeeduino_xiao_ble
    keymap: qwerty
    format: dongle
    shield: totem_dongle dongle_screen
    artifact-name: totem_qwerty_dongle_yads

  - board: nice_nano_v2
    keymap: qwerty
    format: dongle
    shield: totem_dongle_cat dongle_display
    artifact-name: totem_qwerty_dongle_cat
    
  - board: nice_nano_v2                                  # <--- add these
    keymap: qwerty
    format: dongle
    shield: totem_dongle_snake snake_adapter  # <---
    artifact-name: totem_qwerty_dongle_snake     
    
  # Firmware Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_totem
